### ISSUE TITLE
[Smart contract] 트랜잭션 sync 처리

### ISSUE THREAD

**Issue by hhkers** [KlayLoan/KlayLoan#11]
- smart contract 내 모든 함수를 syncrhronized block으로 보장하여 이중계약 등 abuse 방지

**Comment by DongyeolLee** [comment]
이거 혹시 만약에 solidity 내부적으로 지원을 하지 않는다면 서버단에서 해결해야할 것 같은데.. 문제는 서버가 증설됐을때 어떻게 글로벌하게 lock 관리 할것인가.. redis 활용?

**Comment by hhkers** [comment]
openzeppelin 내 ReentrancyGuard 를 사용함으로써 해결 가능.
